// Maps country names used in our data (org.country, and champion/runnerUp/
// thirdPlace/fourthPlace for national-scope competitions) to FIFA's 3-letter
// country codes — the same codes used on broadcast score graphics (ARG, GER,
// NED, etc). Not identical to ISO 3166-1 alpha-3 in every case (e.g. Germany
// is GER here vs DEU in ISO; Netherlands is NED vs NLD) — FIFA's own codes
// are what we're matching, since they're the more recognizable convention.
//
// Covers all 211 current FIFA member associations plus Monaco (not a FIFA
// member, but included since AS Monaco is referenced via lib/clubs.ts).
const COUNTRY_CODES: Record<string, string> = {
  Afghanistan: "AFG",
  Albania: "ALB",
  Algeria: "ALG",
  "American Samoa": "ASA",
  Andorra: "AND",
  Angola: "ANG",
  Anguilla: "AIA",
  "Antigua and Barbuda": "ATG",
  Argentina: "ARG",
  Armenia: "ARM",
  Aruba: "ARU",
  Australia: "AUS",
  Austria: "AUT",
  Azerbaijan: "AZE",
  Bahamas: "BAH",
  Bahrain: "BHR",
  Bangladesh: "BAN",
  Barbados: "BRB",
  Belarus: "BLR",
  Belgium: "BEL",
  Belize: "BLZ",
  Benin: "BEN",
  Bermuda: "BER",
  Bhutan: "BHU",
  Bolivia: "BOL",
  "Bosnia and Herzegovina": "BIH",
  Botswana: "BOT",
  Brazil: "BRA",
  "British Virgin Islands": "VGB",
  Brunei: "BRU",
  Bulgaria: "BUL",
  "Burkina Faso": "BFA",
  Burundi: "BDI",
  Cambodia: "CAM",
  Cameroon: "CMR",
  Canada: "CAN",
  "Cape Verde": "CPV",
  "Cayman Islands": "CAY",
  "Central African Republic": "CTA",
  Chad: "CHA",
  Chile: "CHI",
  China: "CHN",
  "Chinese Taipei": "TPE",
  Colombia: "COL",
  Comoros: "COM",
  Congo: "CGO",
  "Cook Islands": "COK",
  "Costa Rica": "CRC",
  Croatia: "CRO",
  Cuba: "CUB",
  Curaçao: "CUW",
  Cyprus: "CYP",
  "Czechia": "CZE",
  "DR Congo": "COD",
  Denmark: "DEN",
  Djibouti: "DJI",
  Dominica: "DMA",
  "Dominican Republic": "DOM",
  Ecuador: "ECU",
  Egypt: "EGY",
  "El Salvador": "SLV",
  England: "ENG",
  "Equatorial Guinea": "EQG",
  Eritrea: "ERI",
  Estonia: "EST",
  Eswatini: "SWZ",
  Ethiopia: "ETH",
  "Faroe Islands": "FRO",
  Fiji: "FIJ",
  Finland: "FIN",
  France: "FRA",
  Gabon: "GAB",
  Gambia: "GAM",
  Georgia: "GEO",
  Germany: "GER",
  Ghana: "GHA",
  Gibraltar: "GIB",
  Greece: "GRE",
  Grenada: "GRN",
  Guam: "GUM",
  Guatemala: "GUA",
  Guinea: "GUI",
  "Guinea-Bissau": "GNB",
  Guyana: "GUY",
  Haiti: "HAI",
  Honduras: "HON",
  "Hong Kong": "HKG",
  Hungary: "HUN",
  Iceland: "ISL",
  India: "IND",
  Indonesia: "IDN",
  Iran: "IRN",
  Iraq: "IRQ",
  Israel: "ISR",
  Italy: "ITA",
  "Ivory Coast": "CIV",
  Jamaica: "JAM",
  Japan: "JPN",
  Jordan: "JOR",
  Kazakhstan: "KAZ",
  Kenya: "KEN",
  Kosovo: "KOS",
  Kuwait: "KUW",
  Kyrgyzstan: "KGZ",
  Laos: "LAO",
  Latvia: "LVA",
  Lebanon: "LBN",
  Lesotho: "LES",
  Liberia: "LBR",
  Libya: "LBY",
  Liechtenstein: "LIE",
  Lithuania: "LTU",
  Luxembourg: "LUX",
  Macau: "MAC",
  Madagascar: "MAD",
  Malawi: "MWI",
  Malaysia: "MAS",
  Maldives: "MDV",
  Mali: "MLI",
  Malta: "MLT",
  Mauritania: "MTN",
  Mauritius: "MRI",
  Mexico: "MEX",
  Moldova: "MDA",
  Monaco: "MON",
  Mongolia: "MNG",
  Montenegro: "MNE",
  Montserrat: "MSR",
  Morocco: "MAR",
  Mozambique: "MOZ",
  Myanmar: "MYA",
  Namibia: "NAM",
  Nepal: "NEP",
  Netherlands: "NED",
  "New Caledonia": "NCL",
  "New Zealand": "NZL",
  Nicaragua: "NCA",
  Niger: "NIG",
  Nigeria: "NGA",
  "North Korea": "PRK",
  "North Macedonia": "MKD",
  "Northern Ireland": "NIR",
  Norway: "NOR",
  Oman: "OMA",
  Pakistan: "PAK",
  Palestine: "PLE",
  Panama: "PAN",
  "Papua New Guinea": "PNG",
  Paraguay: "PAR",
  Peru: "PER",
  Philippines: "PHI",
  Poland: "POL",
  Portugal: "POR",
  "Puerto Rico": "PUR",
  Qatar: "QAT",
  "Republic of Ireland": "IRL",
  Romania: "ROU",
  Russia: "RUS",
  Rwanda: "RWA",
  "Saint Kitts and Nevis": "SKN",
  "Saint Lucia": "LCA",
  "Saint Vincent and the Grenadines": "VIN",
  Samoa: "SAM",
  "San Marino": "SMR",
  "Saudi Arabia": "KSA",
  Scotland: "SCO",
  Senegal: "SEN",
  Serbia: "SRB",
  Seychelles: "SEY",
  "Sierra Leone": "SLE",
  Singapore: "SGP",
  Slovakia: "SVK",
  Slovenia: "SVN",
  "Solomon Islands": "SOL",
  Somalia: "SOM",
  "South Africa": "RSA",
  "South Korea": "KOR",
  "South Sudan": "SSD",
  Spain: "ESP",
  "Sri Lanka": "SRI",
  Sudan: "SDN",
  Suriname: "SUR",
  Sweden: "SWE",
  Switzerland: "SUI",
  Syria: "SYR",
  "São Tomé and Príncipe": "STP",
  Tahiti: "TAH",
  Tajikistan: "TJK",
  Tanzania: "TAN",
  Thailand: "THA",
  "Timor-Leste": "TLS",
  Togo: "TOG",
  Tonga: "TGA",
  "Trinidad and Tobago": "TRI",
  Tunisia: "TUN",
  Türkiye: "TUR",
  Turkmenistan: "TKM",
  "Turks and Caicos Islands": "TCA",
  "U.S. Virgin Islands": "VIR",
  Uganda: "UGA",
  Ukraine: "UKR",
  "United Arab Emirates": "UAE",
  "United States": "USA",
  Uruguay: "URU",
  Uzbekistan: "UZB",
  Vanuatu: "VAN",
  Venezuela: "VEN",
  Vietnam: "VIE",
  Wales: "WAL",
  Yemen: "YEM",
  Zambia: "ZAM",
  Zimbabwe: "ZIM",
};

// A handful of confederation members that are NOT FIFA members (see
// docs/organizations.md) also need flag lookups, since they appear as
// org.country values just like any FIFA member.
const NON_FIFA_TERRITORY_CODES: Record<string, string> = {
  "Bonaire": "BON",
  "French Guiana": "GUF",
  "Guadeloupe": "GLP",
  "Kiribati": "KIR",
  "Martinique": "MTQ",
  "Northern Mariana Islands": "NMI",
  "Réunion": "REU",
  "Saint Martin": "MAF",
  "Sint Maarten": "SXM",
  "Tuvalu": "TUV",
  "Zanzibar": "ZAN",
};

export function getCountryCode(name: string): string | undefined {
  return COUNTRY_CODES[name] ?? NON_FIFA_TERRITORY_CODES[name];
}
